### ISSUE TITLE
Make the bot can backup your all server messages? 

### ISSUE THREAD

**Issue by Matsko3** [Magic-Bots/xenon#54] opened 2019-08-20 23:48 UTC
#53  What about make bot can backup your all server messages just like if you have many messages in your server and you don't want to lose it then you can backup and not lose it i think that would be helpful for me and people.

**Comment by ThatLifeofGames** [comment] 2019-08-20 23:54
Literally an exact dupe of #53
Not possible anyway so both issues will remain closed

**Closed as completed by ThatLifeofGames** 2019-08-20 23:54 UTC
