### ISSUE TITLE
x!copy copies emotes?

### ISSUE THREAD

**Issue by buthed010203** [Magic-Bots/xenon#15] opened 2018-10-15 19:40 UTC
Pretty self explanatory, x!copy should be able to clone the emotes (suggesting this for copy as im sure the bot backing up and storing emotes would get very heavy well at least assuming the copy command isnt storing the server as well)

**Comment by merlinfuchs** [comment] 2018-11-19 16:23
The problem is not the space in the database, but the time it takes to add emojis to discord. That would block all other processes in the bot.

**Comment by buthed010203** [comment] 2018-11-19 17:17
Ah makes sense, feels bad

**Comment by buthed010203** [comment] 2018-11-19 17:20
When you say it would block **all** other processes do you mean everything in the bot or just the rest of the backup? (I would assume the rest cause of the upload size)

**Comment by merlinfuchs** [comment] 2018-11-19 18:05
It definitely blocks the loading process of that backup and may block the whole bot

**Comment by buthed010203** [comment] 2018-11-19 20:38
Ah ok, if it was just that backup then I would say to just load it at the end.

**Comment by ThatLifeofGames** [comment] 2019-07-31 10:29
Done in xenon turbo, closing https://thatlifeofgames.com/img/1564568976.png

**Closed as completed by ThatLifeofGames** 2019-07-31 10:29 UTC
Labels: enhancement
